name: Docker Image CI

on:
  push:
  workflow_dispatch:
    inputs:
      msg:
        description: "Msg instead of commit log"
        required: true
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: Github Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_GITHUB_APP_TOKEN  }}
        SLACK_CHANNEL: "#slack-watchdog"
        SLACK_ICON: https://avatars.githubusercontent.com/u/44036562?s=48&v=4
        SLACK_FOOTER: ""
        MSG_MINIMAL: true
        SLACK_MESSAGE: |
          test